"""initial schema

Revision ID: b039b489b807
Revises: 
Create Date: 2026-06-26 16:43:17.952088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'b039b489b807'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('parser_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_parsed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('category', sa.Enum('lab', 'doctor_visit', 'diagnostics', 'procedure', name='service_category'), nullable=False),
    sa.Column('synonyms', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_service_synonyms_gin', 'services', ['synonyms'], unique=False, postgresql_using='gin')
    op.create_table('clinics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('city_id', sa.UUID(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('working_hours', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinics_city_id'), 'clinics', ['city_id'], unique=False)
    op.create_table('raw_prices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parser_source_id', sa.UUID(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=True),
    sa.Column('raw_clinic_name', sa.String(length=255), nullable=False),
    sa.Column('raw_service_name', sa.String(length=500), nullable=False),
    sa.Column('raw_price', sa.String(length=100), nullable=False),
    sa.Column('raw_currency', sa.String(length=10), nullable=True),
    sa.Column('raw_duration', sa.String(length=100), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_processed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parser_source_id'], ['parser_sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('checksum')
    )
    op.create_index('ix_raw_price_is_processed', 'raw_prices', ['is_processed'], unique=False)
    op.create_index('ix_raw_price_parser_parsed_at', 'raw_prices', ['parser_source_id', 'parsed_at'], unique=False)
    op.create_table('prices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('raw_price_id', sa.UUID(), nullable=True),
    sa.Column('price_kzt', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.Enum('KZT', 'USD', name='currency'), server_default='KZT', nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raw_price_id'], ['raw_prices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_price_clinic_service_active', 'prices', ['clinic_id', 'service_id', 'is_active'], unique=False)
    op.create_index('ix_price_parsed_at', 'prices', ['parsed_at'], unique=False)
    op.create_index('ix_price_service_active_kzt', 'prices', ['service_id', 'is_active', 'price_kzt'], unique=False)
    op.create_table('unmatched_services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('raw_price_id', sa.UUID(), nullable=False),
    sa.Column('raw_service_name', sa.String(length=500), nullable=False),
    sa.Column('parser_source_id', sa.UUID(), nullable=False),
    sa.Column('suggested_service_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'matched', 'rejected', name='unmatched_status'), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parser_source_id'], ['parser_sources.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['raw_price_id'], ['raw_prices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['suggested_service_id'], ['services.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unmatched_services')
    op.drop_index('ix_price_service_active_kzt', table_name='prices')
    op.drop_index('ix_price_parsed_at', table_name='prices')
    op.drop_index('ix_price_clinic_service_active', table_name='prices')
    op.drop_table('prices')
    op.drop_index('ix_raw_price_parser_parsed_at', table_name='raw_prices')
    op.drop_index('ix_raw_price_is_processed', table_name='raw_prices')
    op.drop_table('raw_prices')
    op.drop_index(op.f('ix_clinics_city_id'), table_name='clinics')
    op.drop_table('clinics')
    op.drop_index('ix_service_synonyms_gin', table_name='services', postgresql_using='gin')
    op.drop_table('services')
    op.drop_table('parser_sources')
    op.drop_table('cities')
    # ### end Alembic commands ###
