"""add parse_runs table

Revision ID: 4f02281c903f
Revises: ed93be77902b
Create Date: 2026-06-26 23:35:52.465487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4f02281c903f'
down_revision: Union[str, None] = 'ed93be77902b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parse_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_slug', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('running', 'success', 'failed', name='parse_run_status'), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('items_saved', sa.Integer(), nullable=True),
    sa.Column('items_skipped', sa.Integer(), nullable=True),
    sa.Column('items_normalized', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_parse_run_source_started', 'parse_runs', ['source_slug', 'started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_parse_run_source_started', table_name='parse_runs')
    op.drop_table('parse_runs')
    # ### end Alembic commands ###
