"""add unique constraint on clinics name city_id

Revision ID: ed93be77902b
Revises: b039b489b807
Create Date: 2026-06-26 23:01:46.933331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ed93be77902b'
down_revision: Union[str, None] = 'b039b489b807'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_clinic_name_city', 'clinics', ['name', 'city_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_clinic_name_city', 'clinics', type_='unique')
    # ### end Alembic commands ###
